name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build and start test containers
        working-directory: ./BE
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to be ready..."
          sleep 20  # Ajusta según tu tiempo de arranque del backend

      - name: Run backend tests
        working-directory: ./BE
        run: docker-compose -f docker-compose.test.yml exec -T backend mvn test

      - name: Tear down containers
        working-directory: ./BE
        run: docker-compose -f docker-compose.test.yml down

  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./FE
        run: npm install

      - name: Run ESLint
        working-directory: ./FE
        run: npm run lint
